name: PlatformIO CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mosquitto:
        image: eclipse-mosquitto:1.6.15
        ports:
          - 1883:1883

    steps:
      - uses: actions/checkout@v6
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio-${{ hashFiles('platformio.ini', 'requirements.txt') }}
      - uses: actions/setup-python@v6
        with:
          python-version: '3.11'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build firmware (compile only)
        run: pio run -e esp32dev

      - name: Run tests
        run: pio test -e esp32dev